<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAJIDs-MBP.fios-router.home" ignored="0" name="Test01" tests="5" failures="1" timestamp="2021-05-26T04:32:05 EDT" time="0.062" errors="0">
  <testcase name="checkoutTest" time="0.009" classname="groupingTests.GroupingTest1"/>
  <testcase name="featuresTest" time="0.001" classname="groupingTests.GroupingTest1"/>
  <testcase name="loginTest" time="0.004" classname="groupingTests.GroupingTest1">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at groupingTests.GroupingTest1.loginTest(GroupingTest1.java:12)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="productTest" time="0.002" classname="groupingTests.GroupingTest1"/>
  <testcase name="trackingTest" time="0.002" classname="groupingTests.GroupingTest1"/>
</testsuite> <!-- Test01 -->
