<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAJIDs-MBP.fios-router.home" ignored="0" name="Test02" tests="5" failures="1" timestamp="2021-05-26T04:32:05 EDT" time="0.012" errors="0">
  <testcase name="checkoutTest" time="0.002" classname="groupingTests.GroupingTest2"/>
  <testcase name="featuresTest" time="0.001" classname="groupingTests.GroupingTest2"/>
  <testcase name="loginTest" time="0.001" classname="groupingTests.GroupingTest2"/>
  <testcase name="productTest" time="0.0" classname="groupingTests.GroupingTest2">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at groupingTests.GroupingTest2.productTest(GroupingTest2.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- productTest -->
  <testcase name="trackingTest" time="0.001" classname="groupingTests.GroupingTest2"/>
</testsuite> <!-- Test02 -->
