<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAJIDs-MBP.fios-router.home" ignored="8" name="GroupingTest1" tests="2" failures="1" timestamp="2021-05-26T05:27:24 EDT" time="0.048" errors="0">
  <testcase name="loginTest" time="0.012" classname="groupingTests.GroupingTest1">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at groupingTests.GroupingTest1.loginTest(GroupingTest1.java:12)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="checkoutTest" time="0.001" classname="groupingTests.GroupingTest1"/>
  <testcase name="trackingTest" time="0.0" classname="groupingTests.GroupingTest2">
    <ignored/>
  </testcase> <!-- trackingTest -->
  <testcase name="loginTest" time="0.0" classname="groupingTests.GroupingTest2">
    <ignored/>
  </testcase> <!-- loginTest -->
  <testcase name="trackingTest" time="0.0" classname="groupingTests.GroupingTest1">
    <ignored/>
  </testcase> <!-- trackingTest -->
  <testcase name="checkoutTest" time="0.0" classname="groupingTests.GroupingTest2">
    <ignored/>
  </testcase> <!-- checkoutTest -->
  <testcase name="productTest" time="0.0" classname="groupingTests.GroupingTest1">
    <ignored/>
  </testcase> <!-- productTest -->
  <testcase name="featuresTest" time="0.0" classname="groupingTests.GroupingTest1">
    <ignored/>
  </testcase> <!-- featuresTest -->
  <testcase name="productTest" time="0.0" classname="groupingTests.GroupingTest2">
    <ignored/>
  </testcase> <!-- productTest -->
  <testcase name="featuresTest" time="0.0" classname="groupingTests.GroupingTest2">
    <ignored/>
  </testcase> <!-- featuresTest -->
</testsuite> <!-- GroupingTest1 -->
